#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
sed -i "s%Whome *=.*$%Whome = \"$CURDIR/priv\"%p" ./src/gchat/gchat_db.go
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"	

gofmt -w src

go install test

export GOPATH="$OLDGOPATH"

echo 'finished'
